<?php

return [
    'items' => [
        ['input1' => '8', 'value1' => '8'],
        ['input1' => '4', 'value1' => '4'],
        ['input1' => '2', 'value1' => '2'],
        ['input1' => '9', 'value1' => '9'],
        ['input1' => '9', 'value1' => '9'],
        ['input1' => '2', 'value1' => '2'],
        ['input1' => '7', 'value1' => '7'],
        ['input1' => '0', 'value1' => '0'],
        ['input1' => '4', 'value1' => '4'],
        ['input1' => '8', 'value1' => '8'],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '5', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '1', 'value1' => ''],
        ['input1' => '7', 'value1' => ''],
        ['input1' => '5', 'value1' => ''],
        ['input1' => '7', 'value1' => ''],
        ['input1' => '1', 'value1' => ''],
        ['input1' => '8', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '0', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '2', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '2', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '0', 'value1' => ''],
        ['input1' => '0', 'value1' => ''],
        ['input1' => '5', 'value1' => ''],
        ['input1' => '8', 'value1' => ''],
        ['input1' => '9', 'value1' => ''],
        ['input1' => '6', 'value1' => ''],
        ['input1' => '7', 'value1' => ''],
        ['input1' => '6', 'value1' => ''],
        ['input1' => '4', 'value1' => ''],
        ['input1' => '9', 'value1' => ''],
        ['input1' => '9', 'value1' => ''],
        ['input1' => '8', 'value1' => ''],
        ['input1' => '4', 'value1' => ''],
        ['input1' => '8', 'value1' => ''],
        ['input1' => '4', 'value1' => ''],
        ['input1' => '2', 'value1' => ''],
        ['input1' => '2', 'value1' => ''],
        ['input1' => '2', 'value1' => ''],
        ['input1' => '4', 'value1' => ''],
        ['input1' => '9', 'value1' => ''],
        ['input1' => '3', 'value1' => ''],
        ['input1' => '2', 'value1' => ''],
        ['input1' => '0', 'value1' => ''],
    ],
];
